### PR TITLE
add did:facebook: method spec

### PR DESCRIPTION
**Pull request by peacekeeper**
Hey I have an idea for a cool new DID method spec - based on Facebook accounts!

Here is the method spec: https://github.com/peacekeeper/did-method-facebook/blob/master/did-method-facebook.md

**NOTE: This is not a serious proposal for a new DID method, but rather a thought experiment about the nature and objectives of DIDs.**

Also see https://github.com/w3c-ccg/did-method-registry/pull/25

### CODE REVIEW

**Comment by talltree** [comment]
@peacekeeper This is bloody brilliant. I was totally on the hook until I got to the punchline in your last line. Touche!

**Comment by msporny** [comment]
Yep, good commentary, we should discuss on a call. It brings up a non-exhaustive list of important questions related to:

* How decentralized must a DID Method be, if at all?
* Do we allow URI Scheme squatting?
* Do we allow trademark squatting?

**Review by msporny — CHANGES_REQUESTED** [review]
Clearly, we can't merge this, even though it meets the published requirements. So, we need new requirements that stops stuff like this happening.

**Comment by msporny** [comment]
@peacekeeper can we close this issue now that there is a DID Decentralization Rubrics work item? 

https://www.w3.org/2019/09/did-wg-charter.html#deliverables

My concern is that people doing PRs against the repo see a fairly controversial PR and come away from the interaction thinking that the group working on this stuff doesn't have a handle on this particular question yet... which would be a negative take away (and not accurate).

**Comment by peacekeeper** [comment]
I agree, the point has been made and thoroughly discussed by the community, and I'm happy with the outcome. Closing.

**Pull request closed without merging**
