### PR TITLE
Added SelfKey ("selfkey") method

### PR DESCRIPTION
**Pull request by cbruguera**
Added DID method as defined by SelfKey with link to the specs document.

### CODE REVIEW

**Comment by ChristopherA** [comment]
Why method name “key” rather than “selfkey”. I’m worried about confusion as there have been several CID schemes (single public key only DIDs) proposed that are just a key.

**Comment by talltree** [comment]
I very strongly agree with Christopher about this. "Key" is not only generic, but could be confusing to developers or others who are new to DID methods. Please rename the method to something specific to Selfkey or the Decentralized Identifier registry that you are targeting.

**Comment by cbruguera** [comment]
Valid points. Method name was changed from "key" to "selfkey" in order to avoid any potential ambiguity or confusion. Thanks for pointing that out.

**Review by msporny — APPROVED** [review]
Author has made changes requested by community. Specification exists. Merging. :)

**Comment by cbruguera** [comment]
Thanks!

**Pull request merged**
