### PR TITLE
Add Pistis DID Method

### PR DESCRIPTION
**Pull request by andreataglia**

### CODE REVIEW

**Comment by talltree** [comment]
This is a good start but the spec currently has no Privacy Considerations or Security Considerations sections. Please see the DID spec for recommendations as to the topics that we strongly recommend be covered in those sections.

**Comment by andreataglia** [comment]
> This is a good start but the spec currently has no Privacy Considerations or Security Considerations sections. Please see the DID spec for recommendations as to the topics that we strongly recommend be covered in those sections.

Sure. We worked on it, please have another look.
Thanks!

**Comment by talltree** [comment]
Thanks for adding reasonably solid Security and Privacy Considerations sections. I think this is ready to add to the registry.

**Review by talltree — APPROVED** [review]
Meets all basic requirements of the DID spec.

**Pull request merged**
