### PR TITLE
Added KILT DID method

### PR DESCRIPTION
**Pull request by maudnals**
This PR is about adding the KILT (https://kilt.io) method specification to the DID Method Registry.
The spec can be found there: https://github.com/KILTprotocol/kilt-did-driver/blob/master/DID%20Method%20Specification.md

Thanks for your feedback!

### CODE REVIEW

**Comment by msporny** [comment]
Reviewed, please expand upon the Security and Privacy considerations section. Once sentence doesn't demonstrate that the proposers have thought about Security and Privacy in depth.

**Comment by talltree** [comment]
I just reviewed the spec and I agree with @msporny that the Privacy and Security Considerations section is not currently adequate. Also, there is not ABNF for your DID syntax, nor an explanation of your encoding of the DID. Since you store DID documents off-chain, there should also be more explanation of how that process works, and the security considerations of off-chain storage (it is an entirely separate attack service from your blockchain).

**Comment by maudnals** [comment]
Hi @talltree , @msporny , thanks for your feedback, understood. 
We're reworking the spec, especially with regards to off-chain storage security considerations; I'll merge conflicting files and notify you here when we think the spec has been correctly updated and is ready for review.
Thanks!

**Comment by maudnals** [comment]
Hi @talltree , @msporny , we've worked on the points you raised and would be glad to get your re-review on this. 

Here is what has changed:
* KILT DID Spec (https://github.com/KILTprotocol/kilt-did-driver/blob/master/DID%20Method%20Specification.md): 
  * More detailed security and privacy section;
  * New paragraph on how to prevent off-chain DID document tampering;
  * Decoupling of the spec from the KILT SDK (see last paragraph dedicated to the mapping between our protocol and SDK);
  * Information on decoding.
* KILT SDK: new capabilities to help mitigate off-chain DID document tampering.

What do you think?

**Comment by msporny** [comment]
> What do you think?

LGTM, merging.

**Pull request merged**
