### PR TITLE
##Add TM DID Method

### PR DESCRIPTION
**Pull request by Colonel86**
The TM DID method specification has been created, which is mainly based on the solidity intelligent contract implementation, followed by the DID-SDK (which deals with the related logic based on DID) and the TMChain(which provides the public chain of DPKI).

### CODE REVIEW

**Comment by talltree** [comment]
I have three issues with this spec:

1. It is harder to understand the structure of the spec than a typical DID method specification. See the [Sovrin DID Method spec](https://sovrin-foundation.github.io/sovrin/spec/did-method-spec-template.html) for an example.
2. It does not yet include a Privacy Considerations section.
3. I am worried about the using the namespace "did:tm:" as I am concerned that it may be semantically misunderstood as a namespace for trademarks ("TM" is the standard business abbreviation for "trademark").

If you can address these three issues I'd be happy to do a second review.

**Comment by TokenTM** [comment]
@talltree We have revised the three issues that you mentioned last time:
1. The structure of the spec has been optimized, especially CRUD description
2. Privacy considerations have been added
3. In order to avoid any misunderstanding, we will use “did:ttm” as new namespace that is abbreviated by domain name “Token.TM”

Thanks for your support.

**Comment by msporny** [comment]
@TokenTM fix the merge conflicts please, we can't pull it in until you fix those.

**Comment by TokenTM** [comment]
@msporny Hi, We have fixed the merge conflicts, thanks.

**Comment by msporny** [comment]
Conflicts remain, please fix.

**Pull request closed without merging**
