### PR TITLE
Add did:trustbloc method.

### PR DESCRIPTION
**Pull request by troyronda**

### CODE REVIEW

**Review by fqutishat — APPROVED** [review]

**Review by msporny — DISMISSED** [review]
The entry is good, the spec is good for the most part. The CRUD operations are light on the details. It would be good to have solid examples in there (perhaps I missed them?). It is missing a privacy and security considerations section, please add one and we'll be good to go to merge this into the DID Method Registry.

**Comment by OR13** [comment]
Seems easy enough to add a paragraph, for reference here is did:v1's:

https://w3c-ccg.github.io/did-method-v1/#privacy-considerations

I have also created https://github.com/w3c-ccg/did-method-registry/issues/85 because I'm not sure we are clearly communicating the requirements needed for registration in the current doc.

**Comment by troyronda** [comment]
Security and privacy considerations sections have been added. Our intention with the CRUD sections is to refer to the Sidetree specifications. We can look at how to make this intention more clear.

**Comment by OR13** [comment]
@troyronda can you resolve the conflict?

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
@msporny @talltree I took a look, looks good to me.

**Review by msporny — APPROVED** [review]

**Pull request merged**
