### PR TITLE
Add OmniOne DID Method

### PR DESCRIPTION
**Pull request by ghost**
This pull request is for adding the OmniOne DID Method Specification.

### CODE REVIEW

**Comment by talltree** [comment]
Thanks for your submission. I reviewed your draft DID method specification. A few comments:

- Check the formatting of your ABNF; it's not coming across as code.
- You don't specify what happens in the Delete operation, i.e., what does the proof do, and what's the end result. Can a DID document be "undeleted"? (The answer should be no.)
- You need to finish the Security and Privacy Consideration sections before we can accept the PR. (Too many early submissions left these blank.)

Thanks.

-

**Comment by OmniOneID** [comment]
- checked ABNF
- removed delete operation
- updated both security and privacy sections of our DID method document.

Thanks for your support.

**Comment by OmniOneID** [comment]
> I've updated both security and privacy sections of our DID method document.
> Thanks for your support.

**Comment by msporny** [comment]
Wait a sec, @OmniOneID ... you closed the pull request w/o it being merged. Is that what you intended to do?

**Comment by OmniOneID** [comment]
Closing was not what i intended, sorry. I reopend this pull request.
Thank you

**Comment by talltree** [comment]
This addresses everything in my original comment except one thing: you removed the "Delete" method but now there's nothing (that I saw) that addresses the "Delete" or "Deactivate" operation that all DID method specifications are required to specify.

So your spec should say how a DID & DID document can be either deleted or deactivated so the DID is effectively terminated/revoked—and cannot be unterminated or unrevoked. If you can add a section specifying how your method accomplishes that operation, then it should be good to go.

Note that some other methods accomplish deactivation by writing a null DID document, and then specifying that that operation cannot be undone, and no further operations can be performed on that DID.

**Comment by OmniOneID** [comment]
I've specified the delete operation on our did specification. 
Thank you for your help.

**Comment by peacekeeper** [comment]
> the "Delete" or "Deactivate" operation that all DID method specifications are required to specify.

Just for the record, there's been discussion whether certain special-purpose DID methods may not support Update or Delete (see https://github.com/w3c-ccg/did-spec/pull/55). This is an open question, but in any case, good to see that OmniOne supports all operations.

**Comment by talltree** [comment]
@peacekeeper has a good point. However in this case it doesn't matter as you have specified a Delete method. I'm satisfied now and support accepting this.

**Comment by OmniOneID** [comment]
What should I do to complete the pull request?

**Comment by msporny** [comment]
> What should I do to complete the pull request?

Fix the merge conflicts.

**Comment by OmniOneID** [comment]
There are no conflicts now.

**Comment by OmniOneID** [comment]
Please confirm that the pull request has been completed?

**Comment by msporny** [comment]
> There are no conflicts now.

Conflicts remain, please fix.

**Comment by msporny** [comment]
>> There are no conflicts now.
>Conflicts remain, please fix.

There are still conflicts, please fix the conflicts so we can merge this in.

**Comment by OmniOneID** [comment]
Would you please check my fix and complete this pull request?

**Review by msporny — APPROVED** [review]

**Pull request merged**
