### PR TITLE
Created Halialabs Emtrust DID method spec

### PR DESCRIPTION
**Pull request by sunilp**
Created Halialabs DID method spec. The implementation is in active development. It is based on Hyperledger fabric, to enable DID for provisioned blockchain

### CODE REVIEW

**Review by msporny — CHANGES_REQUESTED** [review]
You are missing a few things in the DID specification, it feels fairly under specified. You don't mention the API calls or how one creates a DID in the ledger. The Security Considerations section is missing. The examples are incorrect (keys missing fragment identifiers, authentication suite misnamed, service not specified. You may want to fix all of these things before we list the DID Method. 

The bare minimum you will need to do is:

1. Add more detail to the DID Create section
2. Add a DID Deactivation section
3. Add a Security Considerations section.
4. Fix the merge conflicts.

**Comment by sunilp** [comment]
Improved readme to include suggested changes. 
- added more details for creation and APIs
- added did revoke section
- added security considerations
- removed services and incomplete proofs section.

**Comment by halialabsdev** [comment]
Had implemented the changed, any more pending issues?

**Comment by sunilp** [comment]
Had implemented the changes requested. Any more pending issues?

**Pull request merged**
