### PR TITLE
Added Jolocom DID Method Specification

### PR DESCRIPTION
**Pull request by chunningham**

### CODE REVIEW

**Comment by talltree** [comment]
I reviewed the spec. I spotted one typo in this string: "From the Ethereum key pair, take the keccak256 has of the public key" ("has" ==> "hash").

Otherwise it looks pretty good, however it is missing any Privacy or Security Considerations sections, which the DID spec emphasizes are very important for DID methods. So I would strongly encourage you to add those sections.

**Comment by chunningham** [comment]
Thanks for your feedback, I've fixed that type and added a privacy and security section.

**Comment by kimdhamilton** [comment]
Can we merge this?

**Comment by talltree** [comment]
I reviewed it again and I think it's sufficient for listing in the registry. So +1 from me.

**Review by msporny — APPROVED** [review]

**Pull request merged**
