### PR TITLE
Signor DID Method

### PR DESCRIPTION
**Pull request by stbeyer**
Method Spec for the Signor DID Method:

Spec: [https://github.com/cryptonicsconsulting/signor-did-contracts/blob/master/did-method-spec.md](https://github.com/cryptonicsconsulting/signor-did-contracts/blob/master/did-method-spec.md)

Thanks!

### CODE REVIEW

**Comment by paulmadsenhed** [comment]
@stbeyer can you clarify the relevance of this DID Method to 'Herdera Hashgraph', as cited?

**Comment by stbeyer** [comment]
> @stbeyer can you clarify the relevance of this DID Method to 'Herdera Hashgraph', as cited?

Our system is designed to work with DIDs deployed on a number of ledgers that allow Ethereum smart contracts. Hedera is one of those that claim to do so, which is of interest to us. 
BTW, I fixed the typo: Herdera --> Hedera

**Comment by paulmadsenhed** [comment]
Thanks for clarification. Yes we do support the EVM so your DID smart contracts should run as is on Hedera. Coincidentally, I just submitted a PR for Hedera's own (non smart contract based) DID Method.

**Review by msporny — APPROVED** [review]
The DID Method meets the minimum requirements for getting into the DID Method registry. Please flesh out the method spec a bit more, I expect that it's not enough to get close to a conforming implementation by just reading the spec. The Privacy Considerations and Security Considerations section needs far more elaboration as well.

Merging.

**Pull request merged**
