### PR TITLE
Requesting add ABT DID method.

### PR DESCRIPTION
**Pull request by dingpl716**

### CODE REVIEW

**Comment by dingpl716** [comment]
+@mave99a

**Comment by talltree** [comment]
I took a look at the ABT DID Method spec and, while it does define how to create an ABT DID, it does not cover the other CRUD operations as required in [Section 6.2 of the DID spec](https://w3c-ccg.github.io/did-spec/#did-methods). For an example of a DID method specification that includes all of these topics, see the [Sovrin DID Spec](https://sovrin-foundation.github.io/sovrin/spec/did-method-spec-template.html). 

Please attend to these details and then we can add your DID method.

**Comment by dingpl716** [comment]
@talltree I have updated the spec. Could you please review it and let me know if it is OK?

Thanks

**Comment by talltree** [comment]
Yes, you now have the full set of CRUD operations specified. I'd strongly recommend you add your own Security and Privacy Considerations sections to your spec, but I believe it's mature enough now to add to the Registry.

Manu?

**Comment by mave99a** [comment]
Thanks @talltree  It's good point to add Security and Privacy Considerations in the document. @dingpl716 can you add it?

**Comment by dingpl716** [comment]
@talltree , I just updated the doc. Could you please give a review again? Thanks.

**Comment by talltree** [comment]
I was finally able to get to look it over again. Your Privacy and Security consideration sections are not very deep but IMHO they are adequate for being listed in the registry. I'm at Rebooting the Web of Trust with Manu so I'll ask him to approve as well.

**Review by msporny — APPROVED** [review]

**Pull request merged**
