### PR TITLE
Add Dock DID method

### PR DESCRIPTION
**Pull request by lovesh**
Signed-off-by: lovesh <lovesh.bond@gmail.com>

### CODE REVIEW

**Review by msporny — CHANGES_REQUESTED** [review]
The DID Method spec is missing standard descriptions of CRUD operations, security considerations section, privacy considerations section. We can't merge it until it at least has the minimum sections required by the DID Core spec. Example of a conforming DID Method spec is here:

https://w3c-ccg.github.io/did-method-v1/

There are also merge conflicts, please fix.

**Comment by msporny** [comment]
Ping, any updates here, @lovesh ?

**Comment by lovesh** [comment]
@msporny Sorry for the delayed response. Will update soon.

**Comment by OR13** [comment]
This repo is gong to get merged into https://github.com/w3c/did-spec-registries soon, and if this PR is not closed by then, it will need to be opened after the migration.

**Comment by OR13** [comment]
This registry has moved here: https://w3c.github.io/did-spec-registries/#did-methods

I suggest closing this PR here / reopening in there.

This PR will be closed shortly.

**Comment by lovesh** [comment]
@msporny Made the suggested changes in the DID method spec. Thanks @OR13 for not closing this.

**Comment by OR13** [comment]
See also: https://github.com/w3c-ccg/community/issues/131

**Comment by lovesh** [comment]
@OR13 Should I open the PR in https://github.com/w3c/did-spec-registries/?

**Comment by OR13** [comment]
@lovesh yea please, and close this one.

**Pull request closed without merging**
