### PR TITLE
Add Alastria DID Method Specification

### PR DESCRIPTION
**Pull request by jesus-alastria**
This pull request is for adding the Alastria DID Method Specification, for DIDs used in [Alastria National Blockchain Ecosystem](https://alastria.io/).

### CODE REVIEW

**Comment by msporny** [comment]
PR looks fine, but has merge conflicts, please rebase and I can pull it in once there are no conflicts.

**Comment by jesus-alastria** [comment]
Fixed. Resolved conflicts that happened because two entries were added since the PR was initially created.

**Comment by msporny** [comment]
Hmm, github is noting that there is still a merge conflict. I'm not in a place where I have access to git and an editor, I can fix it when I get the chance. If you fix it before I do, I can just pull it in.

**Comment by jesus-alastria** [comment]
Creating another PR.

**Pull request closed without merging**
