### PR TITLE
Add did:dom: method

### PR DESCRIPTION
**Pull request by ricjcosme**
This PR adds the did:dom: method to the registry following https://github.com/decentralized-identity/universal-resolver/pull/11#issuecomment-373670856 item 2. recommendation.

### CODE REVIEW

**Comment by ricjcosme** [comment]
Can you merge this?

**Comment by msporny** [comment]
Conflicts, can't merge. Someone removed the ERC725 method. Please fix the PR so we can pull it in.

**Comment by ricjcosme** [comment]
The ERC725 method wasn't removed - the previous PR's merge ([here](https://github.com/w3c-ccg/did-method-registry/commit/bc1700ccd5135c16f4cd74b0cd34a0b90f83b3a7)) added it twice:

Line https://github.com/w3c-ccg/did-method-registry/blob/bc1700ccd5135c16f4cd74b0cd34a0b90f83b3a7/index.html#L172 to https://github.com/w3c-ccg/did-method-registry/blob/bc1700ccd5135c16f4cd74b0cd34a0b90f83b3a7/index.html#L185 has now the exact same content as in lines https://github.com/w3c-ccg/did-method-registry/blob/bc1700ccd5135c16f4cd74b0cd34a0b90f83b3a7/index.html#L260 to https://github.com/w3c-ccg/did-method-registry/blob/bc1700ccd5135c16f4cd74b0cd34a0b90f83b3a7/index.html#L273

which are the new lines that my PR was also adding, hence the conflict.

How do you want to solve this? Do we leave the ERC725 method there twice and I fix the PR based on that or the current PR conflict is solved by choosing my content over, and having ERC725 there once?

**Comment by peacekeeper** [comment]
Hmm it was probably me who somehow messed up the `erc725` entry. Not sure how to best fix this, @msporny ?

**Comment by dlongley** [comment]
@ricjcosme,

Can you just rebase this PR (or close and create a new one if you don't have experience with rebasing) such that its changes will produce the correct registry? (i.e. erc725 just once, and the new did:dom method).

**Comment by ricjcosme** [comment]
Hi @dlongley, better create a new PR - tried rebasing but not that really used doing it.

**Review by kimdhamilton — COMMENTED** [review]
We need a method spec link for this

**Pull request closed without merging**
