### PR TITLE
add MOAC DID

### PR DESCRIPTION
**Pull request by coolcat2012**

### CODE REVIEW

**Review by talltree — COMMENTED** [review]
I reviewed the spec and, while it is complete—and includes a Security and Privacy Considerations section—it's also very light, i.e., this is one of the shortest DID method specifications submitted.

For example, the privacy and security section has just two paragraphs, when the set of privacy and security considerations that should be considered in the DID spec include many items you do not even mention.

So I would encourage you to consider at least adding more depth to your Privacy and Security Considerations sections before we approve this.

**Comment by msporny** [comment]
> this is one of the shortest DID method specifications submitted.

This is also my biggest concern... your spec doesn't really specify anything in detail. If I had to implement it, I wouldn't know where to start. I tried digging around in your source code repositories to find something, but couldn't figure out which one implements your DID methods, etc.

Here's an example of a DID Method that provides at least a decent bit of information related to the DID Method (request/responses, etc.):

https://w3c-ccg.github.io/didm-veres-one/

**Comment by msporny** [comment]
Does PR #59 supersede this PR? Should we close this PR?

**Comment by msporny** [comment]
Closing after merging PR #59.

**Pull request closed without merging**
