### PR TITLE
Add IoTeX DID Method Registry

### PR DESCRIPTION
**Pull request by lizhefeng**

### CODE REVIEW

**Comment by davidlehn** [comment]
The iotex-did repository doesn't exist.

**Comment by lizhefeng** [comment]
@davidlehn Please try again.

**Review by hank1106 — COMMENTED** [review]
Looks good!

**Comment by msporny** [comment]
The DID Method specification is missing the "Security and Privacy Considerations" section.

**Comment by lizhefeng** [comment]
@msporny Security and Privacy Considerations are added as two separate sections. Please take a look again.

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
> @msporny Security and Privacy Considerations are added as two separate sections. Please take a look again.

Thank you, approved. Merging.

**Pull request merged**
